package be.steria.datapoc.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-16T09:44:52.046+02:00
 * Generated source version: 2.6.1
 * 
 */
@SuppressWarnings("restriction")
@WebService(targetNamespace = "http://datapoc.steria.be/services", name = "PersonService")
@XmlSeeAlso({be.steria.datapoc.model.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PersonService {

    @WebResult(name = "serviceResponse", targetNamespace = "http://datapoc.steria.be/model", partName = "response")
    @WebMethod(action = "http://steria.be.datapoc/services/deletePerson")
    public be.steria.datapoc.model.ServiceResponse deletePerson(
        @WebParam(partName = "deletePersonRequest", name = "deletePersonRequest", targetNamespace = "http://datapoc.steria.be/model")
        be.steria.datapoc.model.DeletePersonRequest deletePersonRequest
    ) throws UnexpectedError;

    @WebResult(name = "serviceResponse", targetNamespace = "http://datapoc.steria.be/model", partName = "response")
    @WebMethod(action = "http://steria.be.datapoc/services/createPerson")
    public be.steria.datapoc.model.ServiceResponse createPerson(
        @WebParam(partName = "createPersonRequest", name = "createPersonRequest", targetNamespace = "http://datapoc.steria.be/model")
        be.steria.datapoc.model.CreatePersonRequest createPersonRequest
    ) throws UnexpectedError;

    @WebResult(name = "serviceResponse", targetNamespace = "http://datapoc.steria.be/model", partName = "response")
    @WebMethod(action = "http://steria.be.datapoc/services/updatePerson")
    public be.steria.datapoc.model.ServiceResponse updatePerson(
        @WebParam(partName = "updatePersonRequest", name = "updatePersonRequest", targetNamespace = "http://datapoc.steria.be/model")
        be.steria.datapoc.model.UpdatePersonRequest updatePersonRequest
    ) throws UnexpectedError;
}
