
package be.steria.datapoc.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-16T09:44:51.906+02:00
 * Generated source version: 2.6.1
 */

@SuppressWarnings("restriction")
@WebFault(name = "unexpectedError", targetNamespace = "http://datapoc.steria.be/model")
public class UnexpectedError extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = -5054188057082019357L;
	private be.steria.datapoc.model.UnexpectedError unexpectedError;

    public UnexpectedError() {
        super();
    }
    
    public UnexpectedError(String message) {
        super(message);
    }
    
    public UnexpectedError(String message, Throwable cause) {
        super(message, cause);
    }

    public UnexpectedError(String message, be.steria.datapoc.model.UnexpectedError unexpectedError) {
        super(message);
        this.unexpectedError = unexpectedError;
    }

    public UnexpectedError(String message, be.steria.datapoc.model.UnexpectedError unexpectedError, Throwable cause) {
        super(message, cause);
        this.unexpectedError = unexpectedError;
    }

    public be.steria.datapoc.model.UnexpectedError getFaultInfo() {
        return this.unexpectedError;
    }
}
