
package be.steria.datapoc.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://datapoc.steria.be/services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @param updatePersonRequest
     * @return
     *     returns be.steria.datapoc.client.ServiceResponse
     * @throws UnexpectedError_Exception
     */
    @WebMethod(action = "http://steria.be.datapoc/services/updatePerson")
    @WebResult(name = "serviceResponse", targetNamespace = "http://datapoc.steria.be/model", partName = "response")
    public ServiceResponse updatePerson(
        @WebParam(name = "updatePersonRequest", targetNamespace = "http://datapoc.steria.be/model", partName = "updatePersonRequest")
        UpdatePersonRequest updatePersonRequest)
        throws UnexpectedError_Exception
    ;

    /**
     * 
     * @param createPersonRequest
     * @return
     *     returns be.steria.datapoc.client.ServiceResponse
     * @throws UnexpectedError_Exception
     */
    @WebMethod(action = "http://steria.be.datapoc/services/createPerson")
    @WebResult(name = "serviceResponse", targetNamespace = "http://datapoc.steria.be/model", partName = "response")
    public ServiceResponse createPerson(
        @WebParam(name = "createPersonRequest", targetNamespace = "http://datapoc.steria.be/model", partName = "createPersonRequest")
        CreatePersonRequest createPersonRequest)
        throws UnexpectedError_Exception
    ;

    /**
     * 
     * @param deletePersonRequest
     * @return
     *     returns be.steria.datapoc.client.ServiceResponse
     * @throws UnexpectedError_Exception
     */
    @WebMethod(action = "http://steria.be.datapoc/services/deletePerson")
    @WebResult(name = "serviceResponse", targetNamespace = "http://datapoc.steria.be/model", partName = "response")
    public ServiceResponse deletePerson(
        @WebParam(name = "deletePersonRequest", targetNamespace = "http://datapoc.steria.be/model", partName = "deletePersonRequest")
        DeletePersonRequest deletePersonRequest)
        throws UnexpectedError_Exception
    ;

}
