
package be.steria.datapoc.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QueryPersons", targetNamespace = "http://services.datapoc.steria.be/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryPersons {


    /**
     * 
     * @param personId
     * @return
     *     returns be.steria.datapoc.client.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonById", targetNamespace = "http://services.datapoc.steria.be/", className = "be.steria.datapoc.client.GetPersonById")
    @ResponseWrapper(localName = "getPersonByIdResponse", targetNamespace = "http://services.datapoc.steria.be/", className = "be.steria.datapoc.client.GetPersonByIdResponse")
    public Person getPersonById(
        @WebParam(name = "personId", targetNamespace = "")
        String personId);

    /**
     * 
     * @return
     *     returns java.util.List<be.steria.datapoc.client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPersons", targetNamespace = "http://services.datapoc.steria.be/", className = "be.steria.datapoc.client.GetAllPersons")
    @ResponseWrapper(localName = "getAllPersonsResponse", targetNamespace = "http://services.datapoc.steria.be/", className = "be.steria.datapoc.client.GetAllPersonsResponse")
    public List<Person> getAllPersons();

}
