
package be.steria.datapoc.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "unexpectedError", targetNamespace = "http://datapoc.steria.be/model")
public class UnexpectedError_Exception
    extends Throwable
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnexpectedError faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UnexpectedError_Exception(String message, UnexpectedError faultInfo) {
    	super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UnexpectedError_Exception(String message, UnexpectedError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: be.steria.datapoc.client.UnexpectedError
     */
    public UnexpectedError getFaultInfo() {
        return faultInfo;
    }

}
